# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-26 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoopfinder', '0006_userreviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreviews',
            name='reviewed_user',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
