# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-27 00:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hoopfinder', '0007_userreviews_reviewed_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreviews',
            name='reviewed_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_reviews', to='hoopfinder.User'),
        ),
    ]
